### ISSUE TITLE
Update to version 19.7.0?

### ISSUE THREAD

**Issue by ryanvolz** [conda-forge/portaudio-feedstock#21]
I maintain a package that uses `portaudio`, and a user of that package reported that they would like to see `portaudio` updated to 19.7.0 since apparently 19.6.0 has problems with newer macOS versions. See https://github.com/ryanvolz/radioconda/issues/110. It looks like there are some particulars which make it so the bot didn't send a PR for that release, so now at least you know it exists! Hopefully and update would be straightforward. Thanks!

**Comment by traversaro** [comment]
Thanks for the report, there is no specific version update error in https://conda-forge.org/status/#version . Anyhow, we can try to manually trigger an update with:

@conda-forge-admin please update version

**Comment by traversaro** [comment]
I guess the source code is posted on a website, so the update bot has no way of knowing if new versions came out.

**Comment by traversaro** [comment]
Fixed in https://github.com/conda-forge/portaudio-feedstock/pull/22 . Downstream projects will need to be rebuilt, see https://github.com/conda-forge/portaudio-feedstock/issues/23 for the related issue.
